### ISSUE TITLE
1 second video generates application crashes.

### ISSUE THREAD

**Issue by rezamusic881** [Jiikuy/VelocityCalculator#13]
#### Project Information
* Repository : https://github.com/jiikuy/velocitycalculator
* Title App : Velocity Caculator
* Publisher App : Georg Rieger

***
***

#### Expected behavior
Supposedly, Video duration of 1 second does not cause the app to stop.

#### Actual behavior
When I record a 1 second video via "Capture Feature", the Application stops. I reentered, then accessed "Open Features" to select the 1 second video, the app paused again.

* Browser : Redmi Note 5A
* System Operating : 7.1.0 Nougat
* App Version : 1.3.1

#### How to reproduce
1. Instal App
2. Open App, Make a video recording for 1 second and Application stopped
3. Lalu masuk kembali dan akses "Buka fitur", pilih kembali video 1 detik. maka aplikasi berhenti lagi.

#### Recording Of The Bug
https://youtu.be/M27LfmSjTbk

#### Logcat
```
--------- beginning of crash
05-18 00:54:44.892  9377  9377 E AndroidRuntime: FATAL EXCEPTION: main
05-18 00:54:44.892  9377  9377 E AndroidRuntime: Process: ch.jiikuy.velocitycalculator, PID: 9377
05-18 00:54:44.892  9377  9377 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at android.view.View.performClick(View.java:5647)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22462)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6361)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	... 9 more
05-18 00:54:44.892  9377  9377 E AndroidRuntime: Caused by: java.lang.NumberFormatException: For input string: "∞"
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at java.lang.Double.parseDouble(Double.java:547)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	at ch.jiikuy.velocitycalculator.CalculateActivity.selectCoordinates(CalculateActivity.java:129)
05-18 00:54:44.892  9377  9377 E AndroidRuntime: 	... 11 more
```

**Comment by Jiikuy** [comment]
Does it work with videos longer than 1  second? The error in the logcat doesn't seem to have anything to do with the video duration.

**Comment by Jiikuy** [comment]
Oh, I didn't see the line at the end. The 1 second measure isn't very accurate - it's an estimation. The actual thing is the number of frames the video has, but this also isn't consistent.
